# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IfXReWTAVe_BaauA80tJjmQdTXNJ3l3
"""

grades=input()
grade_list=grades.split()
fail_count=0
total=0

grade_list = [int(g) for g in grade_list]

max_grade = grade_list[0]
min_grade = grade_list[0]

for grade in grade_list:
    total += grade
    if grade < 60:
        fail_count += 1
    if grade > max_grade:
        max_grade = grade
    if grade < min_grade:
        min_grade = grade
print(fail_count)
print(max)
print(min)
print(total/len(grade_list))
