# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7bjZY_ywSppjgDnKttTz_Zv8igU2p60
"""



grades=input()
grade_list=grades.split()
fail_count=0
max=grade_list[0]
min=grade_list[0]
for grade in grade_list:
  if int(grade)<60:
    fail_count+=1
  if grade_list[grade] > max:
    max=grade_list[grade]
  if grade_list[grade] < min:
    min=grade_list[grade]
print(fail_count)
print(max)
print(min)