# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IfXReWTAVe_BaauA80tJjmQdTXNJ3l3
"""

score=input().split()
count=0
total=0
for i in len(score):
  if score[i]<60:
    count=count+1
  total=total+int(score[i])

print(count)
print(total/len(score))